title: Ryan Burns # website title here
logo: "/images/Headshot.jpg?raw=true" # photo or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. in Data Science candidate at Northwestern University completing the Artificial Intelligence Specialization (expected May 2022).
  <br><br>
  I joined AIR Communities as an Innovation & Automation Associate in November 2021. I am thrilled to have the opportunity to apply my knowledge of automation and AI within my daily responsibilities, and I remain eager to tackle compelling business problems in novel environments.
  <br><br>
  <a href="https://www.linkedin.com/in/ryanmburns93/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-FRX1KQFP64
