title: Ryan Burns # website title here
logo: "/images/Ryan_Headshot.jpg?raw=true" # photo or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS in Data Science, Artificial Intelligence specialization completed through Northwestern University in June 2022.
  <br><br>
  Machine Learning & Automation Associate, AIR Communities
  <br><br>
  <a href="https://www.linkedin.com/in/ryanmburns93/" target="_blank">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/ryanmburns93/" target="_blank">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-FRX1KQFP64